# Generated by Django 4.0.1 on 2022-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('infoId', models.AutoField(primary_key=True, serialize=False)),
                ('numcin', models.CharField(max_length=500)),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=500)),
                ('infraction', models.CharField(max_length=500)),
            ],
        ),
    ]
